#!/bin/bash
#
# This file echoes color codes to the terminal to demonstrate what's available.
# Each line is the color code of one forground color (default + 16 escapes),
# followed by a test use on all nine background colors (default + 8 escapes).
#
# See https://en.wikipedia.org/wiki/ANSI_escape_code
#

TEXT='gYw'   # The test text
SPACER=' '
FGS='m 1m 30m 1;30m 31m 1;31m 32m 1;32m 33m 1;33m 34m 1;34m 35m 1;35m 36m 1;36m 37m 1;37m'
BGS='40m 41m 42m 43m 44m 45m 46m 47m'

echo -en "\n              "
for bg in $BGS; do
  echo -n "   $bg  "
done
echo

for FG in $FGS; do
  printf "%6s \033[$FG  $TEXT  " $FG
  for BG in $BGS; do
    echo -en "${SPACER}\033[$FG\033[$BG  $TEXT  \033[0m"
  done
  echo
done
echo
