#!/usr/bin/env bash
#
# This file echoes color codes to the terminal to demonstrate what's available.
# Each line is the color code of one forground color (default + 16 escapes),
# followed by a test use on all nine background colors (default + 8 escapes).
#
# See https://en.wikipedia.org/wiki/ANSI_escape_code
#

text='gYw'   # The test text
SPC=' '
FGS='0 1 30 1;30 31 1;31 32 1;32 33 1;33 34 1;34 35 1;35 36 1;36 37 1;37'
BGS='40 41 42 43 44 45 46 47'

echo -en "\n              "
for bg in $BGS; do
  echo -n "${SPC}  ${bg}m  "
done
echo

for fg in $FGS; do
  printf "%6s \033[${fg}m  $text  " "${fg}m"
  for bg in $BGS; do
    echo -en "${SPC}\033[${fg}m\033[${bg}m  $text  \033[0m"
  done
  echo
done
echo
